#! /bin/python3

import time
import subprocess

def main():
    fliptable = "fortune flip | cowsay -f flip"
    resettable = "fortune reset | cowsay -f reset"

    while True:
        time.sleep(2)
        subprocess.call(fliptable, shell=True)
        time.sleep(2)
        subprocess.call(resettable, shell=True)
        print("\n")

if __name__ == "__main__":
    main()
